# Generated by Django 3.1.3 on 2020-11-29 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_subjects_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='app.student'),
        ),
    ]
