# Generated by Django 3.1.3 on 2020-11-29 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
